%% Fisrt step in the analysis correcting the files to store info about the finger 

clear; close all;  % clear workspace and close any figures

PATHTORAW = '';            % >>> POINT TO THE LOCATION OF RAW DATA
path_active_correct = '';  % >>> SET PATH for saving active files after correcting classes
path_passive_correct = ''; % >>> SET PATH for saving  passive files after correcting classes

% call utility script where some functions are defined
func = utility.m;

%% FILES
active_filenames = { 'H07_Exp1_left' 'H07_Exp1_right' ... 
                     'H08_Exp1_left' 'H08_Exp1_right' ...
                     'H10_Exp1_left' 'H10_Exp1_right' ...
                     'H11_Exp1_left' 'H11_Exp1_right' ...
                     'H14_Exp1_left' 'H14_Exp1_right' ...
                     'H16_Exp1_left' 'H16_Exp1_right' ...
                     'H17_Exp1_left' 'H17_Exp1_right' ...
                     'H19_Exp1_left' 'H19_Exp1_right' ...
                     'H20_Exp1_left' 'H20_Exp1_right' ... 
                     'H22_Exp1_left' 'H22_Exp1_right' ...
                     'H23_Exp1_left' 'H23_Exp1_right' ...
                     'H25_Exp1_left' 'H25_Exp1_right' ...
                     'P04_Exp1_left' 'P04_Exp1_right' ...
                     'P07_Exp1_left' 'P07_Exp1_right' ...
                     'P08_Exp1_left' 'P08_Exp1_right' ...
                     'P10_Exp1_left' 'P10_Exp1_right' ...
                     'P12_Exp1_left' 'P12_Exp1_right' ...
                     'P13_Exp1_left' 'P13_Exp1_right' ...
                     'P14_Exp1_left' 'P14_Exp1_right' ...
                     'P15_Exp1_left' 'P15_Exp1_right' ...
                     'P16_Exp1_left' 'P16_Exp1_right' ...
                     'P17_Exp1_left' 'P17_Exp1_right' ...
                     'P18_Exp1_left' 'P18_Exp1_right' ...
                     'P19_Exp1_left' 'P19_Exp1_right' ...
                     'P20_Exp1_left' 'P20_Exp1_right' };

passive_filenames = { 'H07_Exp2_left' 'H07_Exp2_right' ... 
                     'H08_Exp2_left' 'H08_Exp2_right' ...
                     'H10_Exp2_left' 'H10_Exp2_right' ...
                     'H11_Exp2_left' 'H11_Exp2_right' ...
                     'H14_Exp2_left' 'H14_Exp2_right' ...
                     'H16_Exp2_left' 'H16_Exp2_right' ...
                     'H17_Exp2_left' 'H17_Exp2_right' ...
                     'H19_Exp2_left' 'H19_Exp2_right' ...
                     'H20_Exp2_left' 'H20_Exp2_right' ...
                     'H21_Exp2_left' 'H21_Exp2_right' ...
                     'H22_Exp2_left' 'H22_Exp2_right' ...
                     'H23_Exp2_left' 'H23_Exp2_right' ...
                     'H25_Exp2_left' 'H25_Exp2_right' ...
                     'P04_Exp2_left_unaff' 'P04_Exp2_right_aff' ...
                     'P07_Exp2_left_aff'   'P07_Exp2_right_unaff' ...
                     'P08_Exp2_left_aff'   'P08_Exp2_right_unaff' ...
                     'P10_Exp2_left_unaff' 'P10_Exp2_right_aff' ...
                     'P12_Exp2_left_aff'   'P12_Exp2_right_unaff' ...
                     'P13_Exp2_left_aff'   'P13_Exp2_right_unaff' ...
                     'P14_Exp2_left_unaff' 'P14_Exp2_right_aff' ...
                     'P15_Exp2_left_unaff' 'P15_Exp2_right_aff' ...
                     'P16_Exp2_left_aff'   'P16_Exp2_right_unaff' ...
                     'P17_Exp2_left_aff'   'P17_Exp2_right_unaff' ...
                     'P18_Exp2_left_aff'   'P18_Exp2_right_unaff' ...
                     'P19_Exp2_left_aff'   'P19_Exp2_right_unaff' ...
                     'P20_Exp2_left_aff'   'P20_Exp2_right_unaff'};

% Stimulus type field needs to contain information about the finger that is being stimulated
% Current .set files only have 'STIM' or 'RESP' to indicate the type of
% event but we want to use finger ids as ADAM classes. 
% The information about the stimulated finger is extracted from event.codes
% and 'STIM' values for event.type and for epoch.enettype are subtitued with 
% finger ids. Note: they both need to be strings for ADAM to use them as classes.

% Correct the stimulus type fields to the correct classes (finger ids)
func.correct_classes(active_filenames, path_active_correct);
func.correct_classes(passive_filenames, path_passive_correct);

