
%% Stacking all trials together to form a "SUPER-SUBJECT"

clear; close all;  % clear workspace and close any figures

path_active_correct = '';  % >>> POINT TO THE LOCATION OF active files after correcting classes
path_passive_correct = ''; % >>> POINT TO THE LOCATION OF passive files after correcting classes

path_super_suject = ''; % >>> SET PATH for saving super-subject stacks

%% FILES
active_filenames = { 'H07_Exp1_left' 'H07_Exp1_right' ... 
                     'H08_Exp1_left' 'H08_Exp1_right' ...
                     'H10_Exp1_left' 'H10_Exp1_right' ...
                     'H11_Exp1_left' 'H11_Exp1_right' ...
                     'H14_Exp1_left' 'H14_Exp1_right' ...
                     'H16_Exp1_left' 'H16_Exp1_right' ...
                     'H17_Exp1_left' 'H17_Exp1_right' ...
                     'H19_Exp1_left' 'H19_Exp1_right' ...
                     'H20_Exp1_left' 'H20_Exp1_right' ... 
                     'H22_Exp1_left' 'H22_Exp1_right' ...
                     'H23_Exp1_left' 'H23_Exp1_right' ...
                     'H25_Exp1_left' 'H25_Exp1_right' };

passive_filenames = { 'H07_Exp2_left' 'H07_Exp2_right' ... 
                     'H08_Exp2_left' 'H08_Exp2_right' ...
                     'H10_Exp2_left' 'H10_Exp2_right' ...
                     'H11_Exp2_left' 'H11_Exp2_right' ...
                     'H14_Exp2_left' 'H14_Exp2_right' ...
                     'H16_Exp2_left' 'H16_Exp2_right' ...
                     'H17_Exp2_left' 'H17_Exp2_right' ...
                     'H19_Exp2_left' 'H19_Exp2_right' ...
                     'H20_Exp2_left' 'H20_Exp2_right' ...
                     'H21_Exp2_left' 'H21_Exp2_right' ...
                     'H22_Exp2_left' 'H22_Exp2_right' ...
                     'H23_Exp2_left' 'H23_Exp2_right' ...
                     'H25_Exp2_left' 'H25_Exp2_right' };

                 
%% Create separate datasets with trials belonging to each finger - SUPER SUBJECT

% Start eeglab
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
% Load the dataset 
EEG = pop_loadset('filename', strcat(active_filenames,'.set'),'filepath', path_active_correct);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 0,'study',0); 
EEG = eeg_checkset( EEG );
% Merge all files together
EEG = pop_mergeset( ALLEEG, [1:length(active_filenames)], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'setname','ss_active', 'savenew', strcat(path_super_suject,'/ss_active'),'gui','off'); 
eeglab redraw; % % Update the EEGLAB window to view changes

%%
% Start eeglab
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
% Load the dataset 
EEG = pop_loadset('filename', strcat(passive_filenames,'.set'),'filepath', path_passive_correct);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 0,'study',0); 
EEG = eeg_checkset( EEG );
% Merge all files together
EEG = pop_mergeset( ALLEEG, [1:length(passive_filenames)], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'setname','ss_passive', 'savenew', strcat(path_super_suject,'/ss_passive'),'gui','off'); 
eeglab redraw; % % Update the EEGLAB window to view changes

%%
